'use client';
import {useState} from 'react';
import WeekCalendar,{useCompactCalendar} from './week-calendar';
import MonthCalendar from './month-calendar';
import {useDiaryAction,ActionFeedback} from './diary-section';
import DayCalendar from './day-calendar';
import {ChevronLeft,ChevronRight,Plus} from 'lucide-react';
import {active,type CoreEntity,type PlanData,type ActualData,type TaskData,type CalendarCategoryData,type SettingsData,type EntityType,type ExecutionSessionData} from '../domain/core';

const pad=(n:number)=>String(n).padStart(2,'0');
const key=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const startWeek=(d:Date)=>{const x=new Date(d);x.setDate(x.getDate()-((x.getDay()+6)%7));x.setHours(0,0,0,0);return x};
type Props={entities:CoreEntity[];create:(t:EntityType,p:Record<string,unknown>)=>Promise<CoreEntity>;update:(e:CoreEntity,p:Record<string,unknown>)=>Promise<void>;openCapture:(taskId?:string,date?:string,start?:string,end?:string)=>void;openEntity:(entity:CoreEntity)=>void;todayOnly?:boolean};

export default function CalendarView({entities,create,update,openCapture,openEntity,todayOnly=false}:Props){
 const action=useDiaryAction(),mobile=useCompactCalendar();
 const plans=active<PlanData>(entities,'plan'),actuals=active<ActualData>(entities,'actual'),sessions=active<ExecutionSessionData>(entities,'executionSession'),tasks=active<TaskData>(entities,'task'),cats=active<CalendarCategoryData>(entities,'calendarCategory'),saved=active<SettingsData>(entities,'settings')[0];
 const [view,setView]=useState<SettingsData['calendarView']>(todayOnly?'day':saved?.payload.calendarView||'day'),[date,setDate]=useState(new Date()),[visible,setVisible]=useState<string[]>(saved?.payload.visibleCalendarCategories||cats.map(c=>c.id)),[showActual,setShowActual]=useState(saved?.payload.showActual??true),[showDeadlines,setShowDeadlines]=useState(saved?.payload.showTaskDeadlines??true),[showManage,setShowManage]=useState(false),[name,setName]=useState(''),[catColor,setCatColor]=useState('#e67ca3'),[catIcon,setCatIcon]=useState(''),[editingCat,setEditingCat]=useState<CoreEntity<CalendarCategoryData>|null>(null);
 const isVisible=(id?:string|null)=>!id||visible.length===0||visible.includes(id),filtered=plans.filter(p=>isVisible(p.payload.calendarCategoryId)),filteredActuals=actuals.filter(a=>isVisible(a.payload.calendarCategoryId)),filteredTasks=tasks.filter(t=>isVisible(t.payload.calendarCategoryId));
 const saveSettings=async(next:Partial<SettingsData>)=>{const payload={...saved?.payload,calendarView:view,visibleCalendarCategories:visible,showPlan:true,showActual,showTaskDeadlines:showDeadlines,...next};if(saved)await update(saved,payload);else await create('settings',payload)};
 const move=(n:number)=>{const x=new Date(date);if(view==='month'){x.setDate(1);x.setMonth(x.getMonth()+n);}else x.setDate(x.getDate()+n*(view==='week'?7:1));setDate(x)};
 const chooseView=(v:SettingsData['calendarView'])=>{setView(v);void action.run(()=>saveSettings({calendarView:v}), '')};
 const toggleCat=(id:string)=>{const base=visible.length?visible:cats.map(c=>c.id),next=base.includes(id)?base.filter(x=>x!==id):[...base,id];setVisible(next);void action.run(()=>saveSettings({visibleCalendarCategories:next}), '')};
 const saveCategory=async()=>{if(!name.trim())return;const payload={name:name.trim(),colorToken:catColor,icon:catIcon,sortOrder:editingCat?.payload.sortOrder??cats.length,archived:false};if(!await action.run(()=>editingCat?update(editingCat,{...editingCat.payload,...payload}):create('calendarCategory',payload)))return;setName('');setCatIcon('');setEditingCat(null)};
 const beginCategory=(c:CoreEntity<CalendarCategoryData>)=>{setEditingCat(c);setName(c.payload.name);setCatColor(c.payload.colorToken);setCatIcon(c.payload.icon||'')};
 const s=startWeek(date),e=new Date(s);e.setDate(e.getDate()+6);const heading=view==='day'?date.toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'long'}):view==='week'?`${s.toLocaleDateString('ja-JP',{year:'numeric',month:'numeric',day:'numeric'})}〜${e.toLocaleDateString('ja-JP',{month:'numeric',day:'numeric'})}`:date.toLocaleDateString('ja-JP',{year:'numeric',month:'long'});
 return <div className="calendar-shell"><section className="panel calendar-toolbar">{!todayOnly&&<div className="view-tabs">{(['day','week','month'] as const).map((v,i)=><button className={view===v?'active':''} aria-pressed={view===v} disabled={action.busy} onClick={()=>chooseView(v)} key={v}>{['日','週','月'][i]}</button>)}</div>}<div className="date-nav"><button aria-label="前へ" onClick={()=>move(-1)}><ChevronLeft/></button><b>{heading}</b><button onClick={()=>setDate(new Date())}>{view==='day'?'今日':view==='week'?'今週':'今月'}</button><button aria-label="次へ" onClick={()=>move(1)}><ChevronRight/></button></div>{!todayOnly&&<button onClick={()=>setShowManage(!showManage)}>カレンダー編集</button>}</section>
 <details className="panel calendar-filter-panel" open={!mobile}><summary>表示するカレンダー・絞り込み</summary><div className="filters"><b>表示</b>{cats.filter(c=>!c.payload.archived).map(c=><label key={c.id}><input type="checkbox" disabled={action.busy} checked={visible.length===0||visible.includes(c.id)} onChange={()=>toggleCat(c.id)}/><i style={{background:c.payload.colorToken}}/>{c.payload.name}</label>)}<label><input type="checkbox" checked={showActual} onChange={e=>{setShowActual(e.target.checked);void action.run(()=>saveSettings({showActual:e.target.checked}), '')}}/>実績</label><label><input type="checkbox" checked={showDeadlines} onChange={e=>{setShowDeadlines(e.target.checked);void action.run(()=>saveSettings({showTaskDeadlines:e.target.checked}), '')}}/>締切</label></div></details>
 <ActionFeedback error={action.error} notice={''}/>{showManage&&<section className="panel manage"><div className="section-title"><h2>カレンダーを管理</h2><button onClick={()=>{setEditingCat(null);setName('');setCatColor('#e67ca3');setCatIcon('')}}><Plus/>新規</button></div><div className="manage-list">{cats.filter(c=>!c.payload.archived).sort((a,b)=>a.payload.sortOrder-b.payload.sortOrder).map(c=><button onClick={()=>beginCategory(c)} key={c.id}><i style={{background:c.payload.colorToken}}/>{c.payload.icon} {c.payload.name}</button>)}</div><div className="inline-add"><input value={name} onChange={e=>setName(e.target.value)} placeholder="例：勉強"/><input className="color-input" aria-label="色" type="color" value={catColor} onChange={e=>setCatColor(e.target.value)}/><input value={catIcon} onChange={e=>setCatIcon(e.target.value)} placeholder="アイコン（任意）"/><button disabled={action.busy} onClick={saveCategory}>{editingCat?'保存':'追加'}</button>{editingCat&&<><button disabled={action.busy} onClick={()=>void action.run(()=>update(editingCat,{...editingCat.payload,sortOrder:Math.max(0,editingCat.payload.sortOrder-1)}))}>上へ</button><button disabled={action.busy} onClick={()=>void action.run(()=>update(editingCat,{...editingCat.payload,sortOrder:editingCat.payload.sortOrder+1}))}>下へ</button><button disabled={action.busy} onClick={()=>void action.run(()=>update(editingCat,{...editingCat.payload,archived:true}))}>アーカイブ</button></>}</div></section>}
 {view==='day'&&<DayCalendar key={key(date)} date={date} plans={filtered} capacityPlans={plans} actuals={showActual?filteredActuals:[]} sessions={sessions} cats={cats} tasks={showDeadlines?filteredTasks:[]} openEntity={openEntity} openCapture={openCapture} update={update}/>} {view==='week'&&<WeekCalendar date={date} plans={filtered} capacityPlans={plans} actuals={showActual?filteredActuals:[]} sessions={sessions} cats={cats} tasks={filteredTasks} showDeadlines={showDeadlines} setDate={setDate} openDay={d=>{setDate(d);chooseView('day')}} openCapture={openCapture} openEntity={openEntity} update={update}/>} {view==='month'&&<MonthCalendar key={date.getFullYear()+'-'+date.getMonth()} date={date} plans={filtered} cats={cats} tasks={showDeadlines?filteredTasks:[]} openDay={d=>{setDate(d);chooseView('day')}} openEntity={openEntity} openCapture={openCapture}/>}</div>
}
