import 'dotenv/config';
import {readFileSync} from 'node:fs';
import {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,type ChatInputCommandInteraction} from 'discord.js';
import {applicationDefault,cert,getApps,initializeApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {executeCommand,executeCommandBatch,parseCommandBatch,parseDiscordCommand,type LiflowCommand} from '../domain/commands.ts';
import {CURRENT_SCHEMA_VERSION} from '../domain/schema.ts';
import type {CoreEntity,EntityType,PlanData} from '../domain/core.ts';

const required=(name:string)=>{const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required in .env.discord`);return value};
const token=required('DISCORD_BOT_TOKEN'),uid=required('LIFLOW_FIREBASE_UID'),allowed=new Set(required('DISCORD_ALLOWED_USER_IDS').split(',').map(x=>x.trim()).filter(Boolean));
const serviceFile=process.env.FIREBASE_SERVICE_ACCOUNT_FILE?.trim();
if(!getApps().length)initializeApp({credential:serviceFile?cert(JSON.parse(readFileSync(serviceFile,'utf8'))):applicationDefault()});
const db=getFirestore(),entities=db.collection('users').doc(uid).collection('entities');
const commands=[
 new SlashCommandBuilder().setName('n').setDescription('今と次の予定を見る'),
 new SlashCommandBuilder().setName('t').setDescription('タスクを追加').addStringOption(o=>o.setName('name').setDescription('内容').setRequired(true)),
 new SlashCommandBuilder().setName('p').setDescription('予定を追加').addStringOption(o=>o.setName('name').setDescription('内容').setRequired(true)).addStringOption(o=>o.setName('start').setDescription('開始 HH:MM').setRequired(true)).addStringOption(o=>o.setName('end').setDescription('終了 HH:MM').setRequired(true)).addStringOption(o=>o.setName('date').setDescription('日付 YYYY-MM-DD（省略時は今日）')),
 new SlashCommandBuilder().setName('a').setDescription('実績を追加').addStringOption(o=>o.setName('name').setDescription('内容').setRequired(true)).addStringOption(o=>o.setName('start').setDescription('開始 HH:MM').setRequired(true)).addStringOption(o=>o.setName('end').setDescription('終了 HH:MM').setRequired(true)).addStringOption(o=>o.setName('date').setDescription('日付 YYYY-MM-DD（省略時は今日）')),
 new SlashCommandBuilder().setName('m').setDescription('収支を追加').addNumberOption(o=>o.setName('amount').setDescription('金額').setRequired(true).setMinValue(1)).addStringOption(o=>o.setName('name').setDescription('内容').setRequired(true)).addStringOption(o=>o.setName('kind').setDescription('支出または収入').addChoices({name:'支出',value:'expense'},{name:'収入',value:'income'})).addStringOption(o=>o.setName('date').setDescription('日付 YYYY-MM-DD（省略時は今日）')).addStringOption(o=>o.setName('category').setDescription('カテゴリ（省略時は内容と同じ）')).addStringOption(o=>o.setName('note').setDescription('メモ')),
 new SlashCommandBuilder().setName('x').setDescription('複数コマンドをまとめて実行').addStringOption(o=>o.setName('commands').setDescription('改行または ; で区切る').setRequired(true)),
];
const pad=(n:number)=>String(n).padStart(2,'0'),dateKey=(d=new Date())=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const iso=(date:string,time:string)=>new Date(`${date}T${time}:00`).toISOString();
const create=async(type:EntityType,payload:Record<string,unknown>)=>{const ref=entities.doc(),now=new Date().toISOString();const entity:CoreEntity={id:ref.id,type,payload,schemaVersion:CURRENT_SCHEMA_VERSION,revision:1,createdAt:now,updatedAt:now,updatedBy:`discord:${uid}`,deletedAt:null};await ref.set(entity);return entity};
const createMany=async(inputs:{type:EntityType;payload:Record<string,unknown>}[])=>{const now=new Date().toISOString(),items=inputs.map(input=>{const ref=entities.doc(),entity:CoreEntity={id:ref.id,type:input.type,payload:input.payload,schemaVersion:CURRENT_SCHEMA_VERSION,revision:1,createdAt:now,updatedAt:now,updatedBy:`discord:${uid}`,deletedAt:null};return {ref,entity}});for(let offset=0;offset<items.length;offset+=400){const batch=db.batch();for(const item of items.slice(offset,offset+400))batch.set(item.ref,item.entity);await batch.commit()}return items.map(item=>item.entity)};
async function showNow(){const snapshot=await entities.where('type','==','plan').get(),now=new Date(),plans=snapshot.docs.map(d=>d.data() as CoreEntity<PlanData>).filter(e=>!e.deletedAt&&new Date(e.payload.endAt)>now).sort((a,b)=>a.payload.startAt.localeCompare(b.payload.startAt));const current=plans.find(p=>new Date(p.payload.startAt)<=now&&now<new Date(p.payload.endAt)),next=plans.find(p=>new Date(p.payload.startAt)>now);return [current?`now  ${current.payload.title} (${new Date(current.payload.startAt).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}-${new Date(current.payload.endAt).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})})`:'now  予定なし',next?`next ${next.payload.title} (${new Date(next.payload.startAt).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})})`:'next 予定なし'].join('\n')}
function structured(i:ChatInputCommandInteraction):LiflowCommand|null{const name=i.commandName;if(name==='n')return {type:'SHOW_NOW'};if(name==='t')return parseDiscordCommand('t',{title:i.options.getString('name',true)});if(name==='m')return parseDiscordCommand('m',{title:i.options.getString('name',true),amount:i.options.getNumber('amount',true),direction:i.options.getString('kind')||'expense',date:i.options.getString('date')||dateKey(),category:i.options.getString('category')||i.options.getString('name',true),note:i.options.getString('note')||''});if(name==='p'||name==='a'){const date=i.options.getString('date')||dateKey();return parseDiscordCommand(name,{title:i.options.getString('name',true),start:iso(date,i.options.getString('start',true)),end:iso(date,i.options.getString('end',true))})}return null}
const client=new Client({intents:[GatewayIntentBits.Guilds]});
client.once('ready',async ready=>{const rest=new REST({version:'10'}).setToken(token),body=commands.map(c=>c.toJSON()),guild=process.env.DISCORD_GUILD_ID?.trim();if(guild)await rest.put(Routes.applicationGuildCommands(ready.user.id,guild),{body});else await rest.put(Routes.applicationCommands(ready.user.id),{body});console.log(`Liflow Discord Bot ready: ${ready.user.tag}`)});
client.on('interactionCreate',async interaction=>{if(!interaction.isChatInputCommand())return;if(!allowed.has(interaction.user.id)){await interaction.reply({content:'このDiscordアカウントはLiflowへの操作を許可されていません。',ephemeral:true});return}await interaction.deferReply({ephemeral:true});try{if(interaction.commandName==='x'){const raw=interaction.options.getString('commands',true),parsed=parseCommandBatch(raw);if(!parsed){const lines=raw.split(/[;\n]+/).map(line=>line.trim()).filter(line=>Boolean(line)&&!/^```(?:text)?$/i.test(line)),invalid=lines.findIndex(line=>!parseCommandBatch(line));throw new Error(`invalid_batch_line:${invalid+1}`)}const results=await executeCommandBatch(parsed,{create,createMany});await interaction.editReply(`${results.length}件をまとめて保存しました。`);return}const command=structured(interaction);if(!command)throw new Error('invalid_command');if(command.type==='SHOW_NOW'){await interaction.editReply(await showNow());return}const result=await executeCommand(command,{create});await interaction.editReply(`保存しました：${String(result.entity?.payload.title||'')}`)}catch(error){console.error(error);const message=error instanceof Error?error.message:'';await interaction.editReply(message.startsWith('invalid_batch_line:')?`形式を読み取れない行があります（${message.split(':')[1]}行目）。`:`Firebaseへの保存に失敗しました（${String((error as {code?:string})?.code||'詳細はBotの黒い画面を確認')}）。`)}});
await client.login(token);
